### ISSUE TITLE
Utilisation de tokens, passwords et d'API keys

### ISSUE THREAD

**Issue by begarco** [WatchDogZZ/android#3]
Comment authentifier l'application sans stocker les données en clair sur GitHub ?

Typiquement pour Travis par exemple avec le déploiement sur GitHub Releases :
```yaml
deploy:
    provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file: "FILE TO UPLOAD"
    skip_cleanup: true
    on:
        tags: true
```
Ou encore avec l'API key de Google Maps et plus tard avec les identifiants de BdD.
